### ISSUE TITLE
Samsung DLNA doesn't work

### ISSUE THREAD

**Issue by DanielFragaBR** [PTCE-Public/popcorn-desktop#9]
With previous versions of Popcorntime, Samsung TV DLNA used to work perfectly. After version 0.3.8.5 (I don't remember the exact version) it started to detect Samsung TV as a chromecast device. Now with the latest git from Popcorntime CE, there's no error about it, but the DLNA doesn't appear either.

```
[27275:0111/043617:INFO:CONSOLE(53)] ""%c[%cERROR%c] TypeError: Cannot read property '1' of null" "color: black;" "color: red;" "color: black;" "TypeError: Cannot read property '1' of null\n    at getFriendlyName (/tmp/.org.chromium.Chromium.69AmLe/node_modules/nodecast-js/lib/Browser.js:37:60)\n    at /tmp/.org.chromium.Chromium.69AmLe/node_modules/nodecast-js/lib/Browser.js:84:32\n    at /tmp/.org.chromium.Chromium.69AmLe/node_modules/nodecast-js/lib/Browser.js:31:13\n    at IncomingMessage.\u003Canonymous\u003E (/tmp/.org.chromium.Chromium.69AmLe/node_modules/nodecast-js/lib/Browser.js:22:20)\n    at emitNone (events.js:70:20)\n    at IncomingMessage.emit (events.js:147:7)\n    at _stream_readable.js:891:16\n    at process._tickCallback (node.js:375:11)"", source: app://host/src/app/app.js (53)
[27275:0111/043617:INFO:CONSOLE(37)] "Uncaught TypeError: Cannot read property '1' of null", source: /tmp/.org.chromium.Chromium.69AmLe/node_modules/nodecast-js/lib/Browser.js (37)
```

Any hints? Thanks.

**Comment by DanielFragaBR** [comment]
Ok, forget it. The author of nodecast-js fixed in version 1.0.2

https://github.com/gyzerok/nodecast-js/issues/5
